//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistory
    {
        public int BhId { get; set; }
        public string emailId { get; set; }
        public Nullable<int> Rid { get; set; }
        public string HotelName { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual HMap HMap { get; set; }
        public virtual Room Room { get; set; }
    }
}
