//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.PaymentBills = new HashSet<PaymentBill>();
        }

        public int Bid { get; set; }
        [Required]
        public string Bname { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email address")]
        public string emailId { get; set; }
        [Required]
        public Nullable<int> Rid { get; set; }
        [Required]
        public Nullable<System.DateTime> Arrival_DateTime { get; set; }
        [Required]
        public Nullable<System.DateTime> Departure_DateTime { get; set; }
        [Required]
        public Nullable<int> No_Of_People { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }

        public virtual HMap HMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBill> PaymentBills { get; set; }
        public virtual customer customer { get; set; }
    }
}
