//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int contactId { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email address")]
        public string emailId { get; set; }
        [Required][MaxLength(500, ErrorMessage ="Message can contain upto 500 characters only")]
        public string Query { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
    }
}
