//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.Bookings = new HashSet<Booking>();
            this.FeedBacks = new HashSet<FeedBack>();
            this.BookingHistories = new HashSet<BookingHistory>();
        }
        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email address")]
        public string emailId { get; set; }
        [Required]
        [RegularExpression("^[a-z,A-Z,0-9]+$", ErrorMessage = "Password should have atleast One UpperCase,One LowerCase and One digit")]
        [MinLength(10, ErrorMessage = "Password has atleast Ten characters")]
        public string cpassword { get; set; }
        [Required]
        public string custname { get; set; }
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Phone number has digits only")]
        [MaxLength(10, ErrorMessage = "Phone number contains atleast Ten digits")]
        public string phone { get; set; }
        [Required]
        public Nullable<System.DateTime> DOB { get; set; }
        [Required]
        public string caddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingHistory> BookingHistories { get; set; }
    }
}
