//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FeedBack
    {
        public int FId { get; set; }
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string emailId { get; set; }
        [Required]
        public string Rating { get; set; }
        [Required]
        public string Comments { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
